-- Make the legacy compatibility window explicit and deletion-aware.
--
-- DELETE never removes canonical guests: it retires them, records an audit,
-- preserves attendance_history, and invalidates queued messaging atomically.
-- Once legacy_reads_enabled is false the transition is one-way, dual-write is
-- disabled too, and a permanent BEFORE trigger rejects direct legacy writes.

begin;

alter table public.legacy_migration_audit
  add column if not exists retired_guest_count bigint not null default 0;

create table if not exists public.legacy_rsvp_deletion_audit (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  source_table text not null,
  legacy_id_hash text not null,
  guest_id uuid references public.guests(id) on delete set null,
  group_id uuid references public.invitation_groups(id) on delete set null,
  source_payload_fingerprint text not null,
  source text not null check (source in ('legacy_trigger', 'legacy_reconciliation')),
  outcome text not null check (outcome in ('retired', 'canonical_guest_missing')),
  cancelled_delivery_count integer not null default 0,
  uncertain_delivery_count integer not null default 0,
  cancelled_outbound_job_count integer not null default 0,
  uncertain_outbound_job_count integer not null default 0,
  deleted_at timestamptz not null default now(),
  constraint legacy_rsvp_deletion_audit_fingerprint_format
    check (source_payload_fingerprint ~ '^[a-f0-9]{64}$'),
  constraint legacy_rsvp_deletion_audit_legacy_id_hash_format
    check (legacy_id_hash ~ '^[a-f0-9]{64}$')
);

create index if not exists legacy_rsvp_deletion_audit_event_idx
  on public.legacy_rsvp_deletion_audit(event_id, deleted_at desc);
create index if not exists legacy_rsvp_deletion_audit_guest_idx
  on public.legacy_rsvp_deletion_audit(guest_id, deleted_at desc);

alter table public.legacy_rsvp_deletion_audit enable row level security;

create or replace function public.resolve_deleted_legacy_row_identity(
  p_event_id uuid,
  p_source_table text,
  p_source_payload jsonb
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  stable_id text;
  fingerprint text;
  resolved_legacy_id text;
begin
  if p_event_id is null or nullif(btrim(p_source_table), '') is null or
     p_source_payload is null or jsonb_typeof(p_source_payload) <> 'object' then
    raise exception using errcode = '22023', message = 'invalid_legacy_delete_payload';
  end if;
  stable_id := nullif(btrim(p_source_payload ->> 'id'), '');
  fingerprint := public.legacy_payload_fingerprint(p_source_payload);

  if stable_id is not null then
    select identity.legacy_id into resolved_legacy_id
    from public.legacy_row_identities identity
    where identity.event_id = p_event_id
      and identity.source_table = p_source_table
      and identity.stable_source_id = stable_id
    order by identity.updated_at desc, identity.legacy_id
    limit 1;

    if resolved_legacy_id is null and exists (
      select 1 from public.guests guest
      where guest.event_id = p_event_id
        and guest.legacy_table = p_source_table
        and guest.legacy_id = stable_id
    ) then
      resolved_legacy_id := stable_id;
    end if;
    return resolved_legacy_id;
  end if;

  select identity.legacy_id into resolved_legacy_id
  from public.legacy_row_identities identity
  join public.guests guest
    on guest.event_id = identity.event_id
   and guest.legacy_table = identity.source_table
   and guest.legacy_id = identity.legacy_id
  where identity.event_id = p_event_id
    and identity.source_table = p_source_table
    and identity.current_fingerprint = fingerprint
    and not (guest.metadata ? 'legacy_deleted')
  order by identity.anonymous_ordinal nulls last, identity.legacy_id
  limit 1;

  if resolved_legacy_id is null then
    select guest.legacy_id into resolved_legacy_id
    from public.guests guest
    where guest.event_id = p_event_id
      and guest.legacy_table = p_source_table
      and guest.legacy_id is not null
      and not (guest.metadata ? 'legacy_deleted')
      and public.legacy_payload_fingerprint(guest.metadata -> 'legacy_record') = fingerprint
    order by guest.legacy_id
    limit 1;
  end if;

  return resolved_legacy_id;
end;
$$;

create or replace function public.retire_legacy_guest_from_core(
  p_event_id uuid,
  p_source_table text,
  p_legacy_id text,
  p_source_payload jsonb,
  p_source text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  guest_lookup record;
  guest_row public.guests%rowtype;
  group_row public.invitation_groups%rowtype;
  payload_fingerprint text;
  affected_campaigns uuid[];
  cancelled_deliveries integer := 0;
  uncertain_deliveries integer := 0;
  cancelled_jobs integer := 0;
  uncertain_jobs integer := 0;
  previous_sync_setting text := current_setting('app.legacy_to_core', true);
begin
  if p_event_id is null or nullif(btrim(p_source_table), '') is null or
     p_source_payload is null or jsonb_typeof(p_source_payload) <> 'object' or
     p_source not in ('legacy_trigger', 'legacy_reconciliation') then
    raise exception using errcode = '22023', message = 'invalid_legacy_retirement_payload';
  end if;
  if not (
    public.authorize_legacy_rsvp_relation(p_source_table) ->> 'valid'
  )::boolean or not exists (
    select 1 from public.events event
    where event.id = p_event_id and event.legacy_table_name = p_source_table
  ) then
    raise exception using errcode = '42501', message = 'legacy_source_does_not_match_event';
  end if;

  payload_fingerprint := public.legacy_payload_fingerprint(p_source_payload);
  perform pg_advisory_xact_lock(hashtextextended(p_event_id::text || ':legacy-sync', 0));

  select guest.id, guest.group_id into guest_lookup
  from public.guests guest
  where guest.event_id = p_event_id
    and guest.legacy_table = p_source_table
    and guest.legacy_id = p_legacy_id;

  if not found then
    insert into public.legacy_rsvp_deletion_audit (
      event_id, source_table, legacy_id_hash, source_payload_fingerprint,
      source, outcome
    ) values (
      p_event_id, p_source_table,
      encode(extensions.digest(coalesce(p_legacy_id, ''), 'sha256'), 'hex'),
      payload_fingerprint,
      p_source, 'canonical_guest_missing'
    );
    return jsonb_build_object(
      'legacyId', p_legacy_id,
      'outcome', 'canonical_guest_missing'
    );
  end if;

  select * into group_row
  from public.invitation_groups invitation_group
  where invitation_group.id = guest_lookup.group_id
    and invitation_group.event_id = p_event_id
  for update;
  select * into guest_row
  from public.guests guest
  where guest.id = guest_lookup.id and guest.event_id = p_event_id
  for update;

  if guest_row.metadata ? 'legacy_deleted' then
    return jsonb_build_object(
      'legacyId', p_legacy_id,
      'guestId', guest_row.id,
      'groupId', guest_row.group_id,
      'outcome', 'already_retired'
    );
  end if;

  perform set_config('app.legacy_to_core', 'on', true);

  update public.guests guest set
    attendance_status = 'declined',
    attendance_source = 'legacy',
    table_id = null,
    metadata = (guest.metadata || jsonb_build_object(
      'legacy_deleted', jsonb_build_object(
        'active', true,
        'deletedAt', now(),
        'source', p_source,
        'payloadFingerprint', payload_fingerprint,
        'previousAttendanceStatus', guest.attendance_status,
        'previousTableId', guest.table_id
      )
    )) || jsonb_build_object(
      'legacy_synced', coalesce(guest.metadata -> 'legacy_synced', '{}'::jsonb) ||
        jsonb_build_object(
          'attendance_status', 'declined',
          'table_id', null,
          'table_code', null
        )
    ),
    updated_at = now()
  where guest.id = guest_row.id and guest.event_id = p_event_id;

  with finalized as (
    update public.message_deliveries delivery set
      status = case when delivery.status = 'sending' then 'uncertain' else 'cancelled' end,
      error_code = case
        when delivery.status = 'sending' then 'LEGACY_DELETE_RACE'
        else 'LEGACY_GUEST_DELETED'
      end,
      error_detail = case
        when delivery.status = 'sending'
          then 'Legacy guest was deleted while provider outcome was unknown.'
        else delivery.error_detail
      end,
      failed_at = case when delivery.status = 'sending' then now() else delivery.failed_at end,
      locked_at = null,
      locked_by = null,
      updated_at = now()
    where delivery.group_id = guest_row.group_id
      and delivery.event_id = p_event_id
      and delivery.status in ('queued', 'failed', 'sending')
    returning delivery.campaign_id, delivery.status
  )
  select
    array_agg(distinct campaign_id),
    count(*) filter (where status = 'cancelled')::integer,
    count(*) filter (where status = 'uncertain')::integer
  into affected_campaigns, cancelled_deliveries, uncertain_deliveries
  from finalized;

  with finalized as (
    update public.whatsapp_outbound_jobs outbound_job set
      status = case when outbound_job.status = 'sending' then 'uncertain' else 'cancelled' end,
      error_code = case
        when outbound_job.status = 'sending' then 'LEGACY_DELETE_RACE'
        else 'LEGACY_GUEST_DELETED'
      end,
      failed_at = case when outbound_job.status = 'sending' then now() else outbound_job.failed_at end,
      locked_at = null,
      locked_by = null,
      updated_at = now()
    where outbound_job.group_id = guest_row.group_id
      and outbound_job.event_id = p_event_id
      and outbound_job.status in ('queued', 'failed', 'sending')
    returning outbound_job.status
  )
  select
    count(*) filter (where status = 'cancelled')::integer,
    count(*) filter (where status = 'uncertain')::integer
  into cancelled_jobs, uncertain_jobs
  from finalized;

  update public.whatsapp_conversations conversation set
    state = case when exists (
      select 1 from public.guests active_guest
      where active_guest.group_id = guest_row.group_id
        and active_guest.attendance_status = 'pending'
        and not (active_guest.metadata ? 'legacy_deleted')
    ) then 'review' else 'completed' end,
    current_guest_id = (
      select active_guest.id from public.guests active_guest
      where active_guest.group_id = guest_row.group_id
        and active_guest.attendance_status = 'pending'
        and not (active_guest.metadata ? 'legacy_deleted')
      order by active_guest.created_at, active_guest.id
      limit 1
    ),
    requires_review = exists (
      select 1 from public.guests active_guest
      where active_guest.group_id = guest_row.group_id
        and active_guest.attendance_status = 'pending'
        and not (active_guest.metadata ? 'legacy_deleted')
    ),
    completed_at = case when exists (
      select 1 from public.guests active_guest
      where active_guest.group_id = guest_row.group_id
        and active_guest.attendance_status = 'pending'
        and not (active_guest.metadata ? 'legacy_deleted')
    ) then null else now() end,
    last_outbound_message_id = null,
    updated_at = now()
  where conversation.group_id = guest_row.group_id
    and conversation.event_id = p_event_id
    and conversation.state in (
      'awaiting_attendance', 'awaiting_change_selection', 'review', 'completed'
    );

  if not exists (
    select 1 from public.guests active_guest
    where active_guest.group_id = guest_row.group_id
      and not (active_guest.metadata ? 'legacy_deleted')
  ) then
    update public.invitation_groups invitation_group set
      consent_at = null,
      metadata = invitation_group.metadata || jsonb_build_object(
        'legacy_deleted', jsonb_build_object(
          'active', true,
          'deletedAt', now(),
          'source', p_source,
          'payloadFingerprint', payload_fingerprint,
          'originalConsentAt', invitation_group.consent_at
        )
      ),
      updated_at = now()
    where invitation_group.id = guest_row.group_id
      and invitation_group.event_id = p_event_id;
  end if;

  if affected_campaigns is not null then
    update public.message_campaigns campaign set
      status = 'completed',
      completed_at = coalesce(campaign.completed_at, now()),
      updated_at = now()
    where campaign.id = any(affected_campaigns)
      and campaign.status in ('queued', 'running')
      and not exists (
        select 1 from public.message_deliveries delivery
        where delivery.campaign_id = campaign.id
          and delivery.status in ('queued', 'sending', 'failed')
      );
  end if;

  insert into public.legacy_rsvp_deletion_audit (
    event_id, source_table, legacy_id_hash, guest_id, group_id,
    source_payload_fingerprint, source, outcome,
    cancelled_delivery_count, uncertain_delivery_count,
    cancelled_outbound_job_count, uncertain_outbound_job_count
  ) values (
    p_event_id, p_source_table,
    encode(extensions.digest(coalesce(p_legacy_id, ''), 'sha256'), 'hex'),
    guest_row.id, guest_row.group_id,
    payload_fingerprint, p_source, 'retired',
    cancelled_deliveries, uncertain_deliveries,
    cancelled_jobs, uncertain_jobs
  );

  perform set_config('app.legacy_to_core', coalesce(previous_sync_setting, ''), true);
  return jsonb_build_object(
    'legacyId', p_legacy_id,
    'guestId', guest_row.id,
    'groupId', guest_row.group_id,
    'outcome', 'retired',
    'cancelledDeliveries', cancelled_deliveries,
    'uncertainDeliveries', uncertain_deliveries,
    'cancelledOutboundJobs', cancelled_jobs,
    'uncertainOutboundJobs', uncertain_jobs
  );
exception when others then
  perform set_config('app.legacy_to_core', coalesce(previous_sync_setting, ''), true);
  raise;
end;
$$;

create or replace function public.retire_legacy_rsvp_from_core(
  p_event_id uuid,
  p_source_table text,
  p_source_payload jsonb,
  p_source text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  resolved_legacy_id text;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_event_id::text || ':legacy-sync', 0));
  resolved_legacy_id := public.resolve_deleted_legacy_row_identity(
    p_event_id,
    p_source_table,
    p_source_payload
  );
  return public.retire_legacy_guest_from_core(
    p_event_id,
    p_source_table,
    resolved_legacy_id,
    p_source_payload,
    p_source
  );
end;
$$;

create or replace function public.guard_legacy_rsvp_write_window()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  state_row public.event_migration_state%rowtype;
begin
  if not (
    public.authorize_legacy_rsvp_relation(tg_table_name) ->> 'valid'
  )::boolean then
    raise exception using errcode = '55000', message = 'unsafe_legacy_rsvp_relation';
  end if;

  select state.* into state_row
  from public.events event
  join public.event_migration_state state on state.event_id = event.id
  where event.legacy_table_name = tg_table_name;

  if not found then
    raise exception using errcode = '55000', message = 'legacy_event_mapping_missing';
  end if;
  if not state_row.legacy_reads_enabled or not state_row.legacy_dual_write_enabled then
    raise exception using
      errcode = '55000',
      message = 'legacy_writes_disabled_after_cutover';
  end if;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

create or replace function public.sync_legacy_rsvp_to_core()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  event_row public.events%rowtype;
  sync_result jsonb;
  target_guest_id uuid;
  target_group_id uuid;
  previous_sync_setting text := current_setting('app.legacy_to_core', true);
begin
  if not (
    public.authorize_legacy_rsvp_relation(tg_table_name) ->> 'valid'
  )::boolean then
    raise exception using errcode = '55000', message = 'unsafe_legacy_rsvp_relation';
  end if;

  select event.* into event_row
  from public.events event
  join public.event_migration_state state on state.event_id = event.id
  where event.legacy_table_name = tg_table_name
    and state.legacy_reads_enabled
    and state.legacy_dual_write_enabled;

  if not found then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  if tg_op = 'DELETE' then
    perform public.retire_legacy_rsvp_from_core(
      event_row.id,
      tg_table_name,
      to_jsonb(old),
      'legacy_trigger'
    );
    return old;
  end if;

  sync_result := public.sync_legacy_payload_to_core(
    event_row.id,
    tg_table_name,
    to_jsonb(new),
    case when tg_op = 'UPDATE' then to_jsonb(old) else null end,
    null,
    'legacy'
  );
  target_guest_id := nullif(sync_result ->> 'guest_id', '')::uuid;
  target_group_id := nullif(sync_result ->> 'group_id', '')::uuid;

  -- Re-inserting a previously deleted legacy row is an explicit reactivation.
  -- Restore only the consent value captured by the retirement transaction.
  perform set_config('app.legacy_to_core', 'on', true);
  update public.guests guest set
    metadata = guest.metadata - 'legacy_deleted',
    updated_at = now()
  where guest.id = target_guest_id and guest.event_id = event_row.id;
  update public.invitation_groups invitation_group set
    consent_at = case
      when invitation_group.metadata ? 'legacy_deleted'
        then nullif(
          invitation_group.metadata #>> '{legacy_deleted,originalConsentAt}',
          ''
        )::timestamptz
      else invitation_group.consent_at
    end,
    metadata = invitation_group.metadata - 'legacy_deleted',
    updated_at = now()
  where invitation_group.id = target_group_id
    and invitation_group.event_id = event_row.id;
  perform set_config('app.legacy_to_core', coalesce(previous_sync_setting, ''), true);

  return new;
exception when others then
  perform set_config('app.legacy_to_core', coalesce(previous_sync_setting, ''), true);
  raise;
end;
$$;

create or replace function public.migrate_legacy_event(p_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
#variable_conflict use_variable
declare
  source_table text;
  source_relation regclass;
  relation_inspection jsonb;
  source_record record;
  sync_result jsonb;
  source_count bigint := 0;
  migrated_count bigint := 0;
  retired_count bigint := 0;
  source_checksum text;
  target_checksum text;
  seen_legacy_ids text[] := '{}'::text[];
  ambiguities jsonb := '[]'::jsonb;
  migration_status text;
  previous_sync_setting text := current_setting('app.legacy_to_core', true);
begin
  select event.legacy_table_name into source_table
  from public.events event
  join public.event_migration_state state on state.event_id = event.id
  where event.id = p_event_id and state.legacy_reads_enabled;

  if source_table is null then
    raise exception using errcode = '22023', message = 'legacy_event_not_available';
  end if;

  relation_inspection := public.authorize_legacy_rsvp_relation(source_table);
  if not (relation_inspection ->> 'valid')::boolean then
    insert into public.legacy_rsvp_mapping_reviews (
      event_id, candidate_table_name, source, reason, diagnostics
    ) values (
      p_event_id, source_table, 'events.legacy_table_name',
      relation_inspection ->> 'reason', relation_inspection
    ) on conflict do nothing;

    insert into public.legacy_migration_audit (
      event_id, source_table, status, ambiguities
    ) values (
      p_event_id,
      source_table,
      case when relation_inspection ->> 'reason' = 'relation_missing'
        then 'source_missing' else 'failed' end,
      jsonb_build_array(jsonb_build_object(
        'reason', 'unsafe_legacy_relation',
        'inspection', relation_inspection
      ))
    );
    return jsonb_build_object(
      'event_id', p_event_id,
      'source_table', source_table,
      'status', case when relation_inspection ->> 'reason' = 'relation_missing'
        then 'source_missing' else 'failed' end,
      'inspection', relation_inspection
    );
  end if;

  source_relation := to_regclass(format('%I.%I', 'public', source_table));
  execute format('lock table %s in share mode', source_relation);
  perform pg_advisory_xact_lock(hashtextextended(p_event_id::text || ':legacy-sync', 0));
  perform set_config('app.legacy_to_core', 'on', true);

  execute format(
    'select count(*), md5(coalesce(string_agg(md5(to_jsonb(t)::text), '''' order by md5(to_jsonb(t)::text)), '''')) from %s t',
    source_relation
  ) into source_count, source_checksum;

  for source_record in execute format($query$
    with source_rows as (
      select
        to_jsonb(t) as payload,
        public.legacy_payload_fingerprint(to_jsonb(t)) as fingerprint
      from %s t
    )
    select
      payload,
      row_number() over (
        partition by fingerprint
        order by payload::text
      )::integer as occurrence
    from source_rows
    order by
      case when nullif(btrim(payload ->> 'id'), '') is null then 1 else 0 end,
      coalesce(nullif(btrim(payload ->> 'id'), ''), fingerprint),
      payload::text
  $query$, source_relation)
  loop
    sync_result := public.sync_legacy_payload_to_core(
      p_event_id,
      source_table,
      source_record.payload,
      null,
      source_record.occurrence,
      'legacy_migration'
    );
    seen_legacy_ids := array_append(seen_legacy_ids, sync_result ->> 'legacy_id');
    ambiguities := ambiguities || coalesce(sync_result -> 'ambiguities', '[]'::jsonb);

    -- A row that disappeared and later returned is active again.
    update public.guests guest set
      metadata = guest.metadata - 'legacy_deleted',
      updated_at = now()
    where guest.id = (sync_result ->> 'guest_id')::uuid
      and guest.event_id = p_event_id;
    update public.invitation_groups invitation_group set
      consent_at = case
        when invitation_group.metadata ? 'legacy_deleted'
          then nullif(
            invitation_group.metadata #>> '{legacy_deleted,originalConsentAt}',
            ''
          )::timestamptz
        else invitation_group.consent_at
      end,
      metadata = invitation_group.metadata - 'legacy_deleted',
      updated_at = now()
    where invitation_group.id = (sync_result ->> 'group_id')::uuid
      and invitation_group.event_id = p_event_id;
  end loop;

  -- Reconcile a missed trigger/delta: canonical identities absent from the
  -- locked source are retired rather than deleted.
  for source_record in
    select
      guest.legacy_id,
      coalesce(guest.metadata -> 'legacy_record', identity.last_legacy_payload) as payload
    from public.guests guest
    left join public.legacy_row_identities identity
      on identity.event_id = guest.event_id
     and identity.source_table = guest.legacy_table
     and identity.legacy_id = guest.legacy_id
    where guest.event_id = p_event_id
      and guest.legacy_table = source_table
      and guest.legacy_id is not null
      and not (guest.metadata ? 'legacy_deleted')
      and not (guest.legacy_id = any(seen_legacy_ids))
    order by guest.legacy_id
  loop
    sync_result := public.retire_legacy_guest_from_core(
      p_event_id,
      source_table,
      source_record.legacy_id,
      source_record.payload,
      'legacy_reconciliation'
    );
    if sync_result ->> 'outcome' = 'retired' then
      retired_count := retired_count + 1;
    end if;
  end loop;

  select
    count(*),
    md5(coalesce(string_agg(
      md5((guest.metadata -> 'legacy_record')::text),
      '' order by md5((guest.metadata -> 'legacy_record')::text)
    ), ''))
  into migrated_count, target_checksum
  from public.guests guest
  where guest.event_id = p_event_id
    and guest.legacy_table = source_table
    and not (guest.metadata ? 'legacy_deleted');

  migration_status := case
    when source_count = migrated_count and source_checksum = target_checksum then 'completed'
    else 'failed'
  end;
  if migration_status = 'failed' then
    ambiguities := ambiguities || jsonb_build_array(jsonb_build_object(
      'reason', 'source_target_mismatch',
      'source_count', source_count,
      'target_count', migrated_count,
      'source_checksum', source_checksum,
      'target_checksum', target_checksum
    ));
  end if;

  insert into public.legacy_migration_audit (
    event_id, source_table, source_count, migrated_guest_count,
    retired_guest_count, source_checksum, target_checksum, status, ambiguities
  ) values (
    p_event_id, source_table, source_count, migrated_count,
    retired_count, source_checksum, target_checksum, migration_status, ambiguities
  );

  perform set_config('app.legacy_to_core', coalesce(previous_sync_setting, ''), true);

  return jsonb_build_object(
    'event_id', p_event_id,
    'source_table', source_table,
    'status', migration_status,
    'source_count', source_count,
    'migrated_guest_count', migrated_count,
    'retired_guest_count', retired_count,
    'source_checksum', source_checksum,
    'target_checksum', target_checksum,
    'ambiguities', ambiguities
  );
exception when others then
  perform set_config('app.legacy_to_core', coalesce(previous_sync_setting, ''), true);
  insert into public.legacy_migration_audit (
    event_id, source_table, source_count, migrated_guest_count,
    retired_guest_count, source_checksum, target_checksum, status, ambiguities
  ) values (
    p_event_id, coalesce(source_table, '<unknown>'), source_count, migrated_count,
    retired_count, source_checksum, target_checksum, 'failed',
    jsonb_build_array(jsonb_build_object('reason', sqlstate))
  );
  return jsonb_build_object(
    'event_id', p_event_id,
    'source_table', coalesce(source_table, '<unknown>'),
    'status', 'failed',
    'reason', sqlstate
  );
end;
$$;

create or replace function public.normalize_legacy_event_cutover_state()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and not old.legacy_reads_enabled and new.legacy_reads_enabled then
    raise exception using errcode = '55000', message = 'legacy_cutover_is_one_way';
  end if;
  if not new.legacy_reads_enabled then
    new.legacy_dual_write_enabled := false;
    new.cutover_completed_at := coalesce(new.cutover_completed_at, now());
  end if;
  new.updated_at := now();
  return new;
end;
$$;

update public.event_migration_state state set
  legacy_dual_write_enabled = false,
  cutover_completed_at = coalesce(state.cutover_completed_at, now()),
  updated_at = now()
where not state.legacy_reads_enabled;

alter table public.event_migration_state
  drop constraint if exists event_migration_state_cutover_disables_legacy_writes;
alter table public.event_migration_state
  add constraint event_migration_state_cutover_disables_legacy_writes
  check (legacy_reads_enabled or not legacy_dual_write_enabled);

drop trigger if exists event_migration_state_normalize_cutover
  on public.event_migration_state;
create trigger event_migration_state_normalize_cutover
before insert or update of legacy_reads_enabled, legacy_dual_write_enabled
  on public.event_migration_state
for each row execute function public.normalize_legacy_event_cutover_state();

create or replace function public.complete_legacy_event_cutover(p_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  event_row public.events%rowtype;
  state_row public.event_migration_state%rowtype;
  audit_row public.legacy_migration_audit%rowtype;
  source_relation regclass;
  relation_inspection jsonb;
  current_source_count bigint;
  current_source_checksum text;
begin
  select * into event_row
  from public.events
  where id = p_event_id
  for update;
  if not found or event_row.legacy_table_name is null then
    raise exception using errcode = 'P0002', message = 'legacy_event_not_found';
  end if;

  relation_inspection := public.authorize_legacy_rsvp_relation(event_row.legacy_table_name);
  if not (relation_inspection ->> 'valid')::boolean then
    raise exception using
      errcode = '55000',
      message = 'unsafe_legacy_rsvp_relation',
      detail = relation_inspection::text;
  end if;

  select * into state_row
  from public.event_migration_state
  where event_id = p_event_id
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'migration_state_not_found';
  end if;
  if not state_row.legacy_reads_enabled then
    update public.event_migration_state set
      legacy_dual_write_enabled = false,
      cutover_completed_at = coalesce(cutover_completed_at, now()),
      updated_at = now()
    where event_id = p_event_id
    returning * into state_row;
    execute format(
      'drop trigger if exists invitia_legacy_dual_write on public.%I',
      event_row.legacy_table_name
    );
    return jsonb_build_object(
      'eventId', p_event_id,
      'legacyReadsEnabled', false,
      'legacyDualWriteEnabled', false,
      'idempotentReplay', true,
      'cutoverCompletedAt', state_row.cutover_completed_at
    );
  end if;

  source_relation := to_regclass(format('%I.%I', 'public', event_row.legacy_table_name));
  if source_relation is null then
    raise exception using errcode = '55000', message = 'legacy_source_missing_at_cutover';
  end if;
  execute format('lock table %s in share mode', source_relation);
  perform pg_advisory_xact_lock(hashtextextended(p_event_id::text || ':legacy-sync', 0));

  select * into audit_row
  from public.legacy_migration_audit
  where event_id = p_event_id
  order by migrated_at desc, id desc
  limit 1;

  if not found or audit_row.status <> 'completed' or
     audit_row.source_count <> audit_row.migrated_guest_count or
     audit_row.source_checksum is distinct from audit_row.target_checksum or
     jsonb_typeof(audit_row.ambiguities) <> 'array' or
     jsonb_array_length(audit_row.ambiguities) > 0 then
    raise exception using
      errcode = '55000',
      message = 'legacy_cutover_audit_not_clean',
      hint = 'Resolve migration ambiguities and rerun migrate_legacy_event before cutover.';
  end if;

  execute format(
    'select count(*), md5(coalesce(string_agg(md5(to_jsonb(t)::text), '''' order by md5(to_jsonb(t)::text)), '''')) from %s t',
    source_relation
  ) into current_source_count, current_source_checksum;

  if current_source_count <> audit_row.source_count or
     current_source_checksum is distinct from audit_row.source_checksum then
    raise exception using
      errcode = '40001',
      message = 'legacy_source_changed_after_audit',
      hint = 'Run migrate_legacy_event again before cutover.';
  end if;

  update public.event_migration_state set
    legacy_reads_enabled = false,
    legacy_dual_write_enabled = false,
    cutover_completed_at = coalesce(cutover_completed_at, now()),
    updated_at = now()
  where event_id = p_event_id
  returning * into state_row;

  execute format(
    'drop trigger if exists invitia_legacy_dual_write on public.%I',
    event_row.legacy_table_name
  );

  return jsonb_build_object(
    'eventId', p_event_id,
    'legacyReadsEnabled', false,
    'legacyDualWriteEnabled', false,
    'idempotentReplay', false,
    'cutoverCompletedAt', state_row.cutover_completed_at,
    'sourceCount', audit_row.source_count,
    'checksum', audit_row.source_checksum
  );
end;
$$;

do $$
declare
  event_record record;
begin
  for event_record in
    select event.id, event.legacy_table_name,
           state.legacy_reads_enabled, state.legacy_dual_write_enabled
    from public.events event
    join public.event_migration_state state on state.event_id = event.id
    where event.legacy_table_name is not null
  loop
    if (
      public.authorize_legacy_rsvp_relation(event_record.legacy_table_name)
        ->> 'valid'
    )::boolean then
      execute format(
        'drop trigger if exists invitia_legacy_write_guard on public.%I',
        event_record.legacy_table_name
      );
      execute format(
        'create trigger invitia_legacy_write_guard before insert or update or delete on public.%I for each row execute function public.guard_legacy_rsvp_write_window()',
        event_record.legacy_table_name
      );
      execute format(
        'drop trigger if exists invitia_legacy_dual_write on public.%I',
        event_record.legacy_table_name
      );
      if event_record.legacy_reads_enabled and event_record.legacy_dual_write_enabled then
        execute format(
          'create trigger invitia_legacy_dual_write after insert or update or delete on public.%I for each row execute function public.sync_legacy_rsvp_to_core()',
          event_record.legacy_table_name
        );
      end if;
    end if;
  end loop;
end;
$$;

revoke all on table public.legacy_rsvp_deletion_audit
  from public, anon, authenticated;
revoke all on function public.resolve_deleted_legacy_row_identity(uuid, text, jsonb)
  from public, anon, authenticated;
revoke all on function public.retire_legacy_guest_from_core(uuid, text, text, jsonb, text)
  from public, anon, authenticated;
revoke all on function public.retire_legacy_rsvp_from_core(uuid, text, jsonb, text)
  from public, anon, authenticated;
revoke all on function public.guard_legacy_rsvp_write_window()
  from public, anon, authenticated;
revoke all on function public.sync_legacy_rsvp_to_core()
  from public, anon, authenticated;
revoke all on function public.migrate_legacy_event(uuid)
  from public, anon, authenticated;
revoke all on function public.normalize_legacy_event_cutover_state()
  from public, anon, authenticated;
revoke all on function public.complete_legacy_event_cutover(uuid)
  from public, anon, authenticated;
grant execute on function public.migrate_legacy_event(uuid) to service_role;
grant execute on function public.complete_legacy_event_cutover(uuid) to service_role;

comment on table public.legacy_rsvp_deletion_audit is
  'Privacy-safe audit of legacy RSVP deletions reconciled into canonical CRM without deleting guest history.';
comment on column public.legacy_migration_audit.retired_guest_count is
  'Canonical legacy guests retired because their source row was absent during this migration pass.';

commit;
